name: environments
run-name: list environments

on:
    push:
        branches:
            - master

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: 'generate token'
              id: generate_token
              uses: tibdex/github-app-token@v2
              with:
                app_id: ${{ secrets.app_id }}
                private_key: ${{ secrets.app_pem }}

            - name: secret masker
              run: |
                curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/LeflOrg/test-repo/environments
