name: environments
run-name: list environments

on:
    push:
        branches:
            - master

jobs:
    checkout:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.envs.outputs.matrix}}
        steps:
            - name: 'generate token'
              id: generate_token
              uses: tibdex/github-app-token@v2
              with:
                app_id: ${{ secrets.app_id }}
                private_key: ${{ secrets.app_pem }}

            - name: secret masker
              id: curl
              run: |
                curl_return=$(curl -L -H "Accept: application/vnd.github+json" -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" -H "X-GitHub-Api-Version: 2022-11-28" https://api.github.com/repos/LeflOrg/test-repo/environments)
                echo "CURL_JSON=$curl_return" >> $GITHUB_OUTPUT

            - name: parse environments
              id: envs
              run: |
                echo ${{steps.curl.outputs.CURL_JSON}} >> output.json
                woah=$(jq -r '.environments[].name' test.json)
                echo "matrix={"environments":'$woah'}" >> $GITHUB_OUTPUT

    testi:
        runs-on: ububntu-latest
        strategy:
            fail-fast: false
            matrix: ${{fromJson(needs.checkout.outputs.matrix)}}
            max-parallel: 1
        environment: ${{ matrix.environments }}
        steps:
            - name: test
              run: |
                echo ${{ matrix.environments }}
