name: environments
run-name: list environments

on:
    push:
        branches:
            - master

jobs:
    checkout:
        runs-on: ubuntu-latest
        outputs:
            matrix: ${{ steps.envs.outputs.matrix}}
        steps:
            - name: 'generate token'
              id: generate_token
              uses: tibdex/github-app-token@v2
              with:
                app_id: ${{ secrets.app_id }}
                private_key: ${{ secrets.app_pem }}

            - name: secret masker
              id: envs
              run: |
                curl -L \
                -H "Accept: application/vnd.github+json" \
                -H "Authorization: Bearer ${{ steps.generate_token.outputs.token }}" \
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository }}/environments \
                -o response.json
                env_names=$(jq '.environments[].name' response.json)
                env_names=$(echo $env_names | sed 's/ /,/g')
                echo 'matrix={"environments":[ '$env_names' ]}'
                echo 'matrix={"environments":[ '$env_names' ]}' >> $GITHUB_OUTPUT

            - name: debug echo
              run: |
                echo ${{ steps.envs.outputs.matrix }}

    testi:
        needs: checkout
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix: ${{fromJson(needs.checkout.outputs.matrix)}}
            max-parallel: 2
        environment: ${{ matrix.environments }}
        steps:
            - name: test
              run: |
                echo ${{ matrix.environments }}
                echo ${{ vars.arvo }}
