name: secret masking
run-name: secret-masking

on:
    push:
        branches:
            - master

jobs:
    checkout:
        runs-on: ubuntu-latest
        steps:
            - name: secret masker
              run: |
                echo '260261263'
                echo ${{ secrets.test_mask }}
